apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jemon.fullname" . }}-api
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  CRED_KEY: {{ .Values.api.secrets.CRED_KEY | quote }}
  AUTH_SECRET: {{ .Values.api.secrets.AUTH_SECRET | quote }}
  ADMIN_USER: {{ .Values.api.secrets.ADMIN_USER | quote }}
  ADMIN_PASSWORD: {{ .Values.api.secrets.ADMIN_PASSWORD | quote }}
