apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jemon.fullname" . }}-config
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
data:
  VICTORIAMETRICS_URL: "http://{{ include "jemon.fullname" . }}-victoriametrics:{{ .Values.victoriametrics.service.port }}"
  VALKEY_URL: "redis://{{ include "jemon.fullname" . }}-valkey:{{ .Values.valkey.service.port }}"
  VMAGENT_SCRAPE_INTERVAL: {{ .Values.config.vmagentScrapeInterval | quote }}
