apiVersion: v1
kind: Service
metadata:
  name: {{ include "jemon.fullname" . }}-snmp-exporter
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
    app.kubernetes.io/component: snmp-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "jemon.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: snmp-exporter
  ports:
    - name: http
      port: 9116
      targetPort: http
      protocol: TCP
