apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jemon.fullname" . }}-snmp-exporter
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
    app.kubernetes.io/component: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: snmp-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: snmp-exporter
    spec:
      containers:
        - name: snmp-exporter
          image: "{{ .Values.snmpExporter.image }}:{{ .Values.snmpExporter.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9116
              protocol: TCP
          resources:
            {{- toYaml .Values.snmpExporter.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
