apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jemon.fullname" . }}-vmagent
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
    app.kubernetes.io/component: vmagent
spec:
  replicas: {{ .Values.vmagent.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: vmagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: vmagent
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vmagent-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: vmagent
          image: "{{ .Values.vmagent.image }}:{{ .Values.vmagent.imageTag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "-promscrape.config=/etc/vmagent/scrape.yml"
            - "-remoteWrite.url=http://{{ include "jemon.fullname" . }}-victoriametrics:{{ .Values.victoriametrics.service.port }}/api/v1/write"
            - "-remoteWrite.url=http://{{ include "jemon.fullname" . }}-vm-rollup:{{ .Values.victoriametricsRollup.service.port }}/api/v1/write"
            - "-remoteWrite.streamAggr.config="
            - "-remoteWrite.streamAggr.config=/etc/vmagent/stream-agg.yml"
          volumeMounts:
            - name: vmagent-config
              mountPath: /etc/vmagent
              readOnly: true
          resources:
            {{- toYaml .Values.vmagent.resources | nindent 12 }}
      volumes:
        - name: vmagent-config
          configMap:
            name: {{ include "jemon.fullname" . }}-vmagent
