apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jemon.fullname" . }}-vmagent
  labels:
    {{- include "jemon.labels" . | nindent 4 }}
    app.kubernetes.io/component: vmagent
data:
  scrape.yml: |
    scrape_configs:
      - job_name: snmp_if_mib
        metrics_path: /snmp
        params:
          auth: [public_v2]
          module: [if_mib]
        static_configs:
          - targets: []  # populated at runtime via configgen
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - replacement: "jemon-snmp-exporter:9116"
            target_label: __address__
          - source_labels: [__param_target]
            target_label: instance
  stream-agg.yml: |
    - match: '{__name__=~"if.+"}'
      interval: 5m
      outputs:
        - total
        - avg
